#
# Copyright (c) 2022, 2024, Oracle and/or its affiliates. All rights reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This code is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 only, as
# published by the Free Software Foundation.  Oracle designates this
# particular file as subject to the "Classpath" exception as provided
# by Oracle in the LICENSE file that accompanied this code.
#
# This code is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# version 2 for more details (a copy is included in the LICENSE file that
# accompanied this code).
#
# You should have received a copy of the GNU General Public License version
# 2 along with this work; if not, write to the Free Software Foundation,
# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
# or visit www.oracle.com if you need additional information or have any
# questions.
#

name: 'Build (android armv7)'

on:
  workflow_call:
    inputs:
      extra-conf-options:
        required: false
        type: string
      make-target:
        required: false
        type: string
        default: 'product-bundles test-bundles'
      debug-levels:
        required: false
        type: string
        default: '[ "debug", "release" ]'
      gcc-major-version:
        required: true
        type: string
      gcc-package-suffix:
        required: false
        type: string
        default: ''
      apt-extra-packages:
        required: false
        type: string
      configure-arguments:
        required: false
        type: string
      make-arguments:
        required: false
        type: string

jobs:
  build-android-armv7:
    name: build
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        debug-level: ${{ fromJSON(inputs.debug-levels) }}
        include:
          - debug-level: debug
            flags: --enable-debug
            suffix: -debug
          - debug-level: release
            flags: --with-debug-level=release --with-native-debug-symbols=none
            suffix: ''

    steps:
      - name: 'Checkout the JDK source'
        uses: actions/checkout@v4

      - name: 'Get the BootJDK'
        id: bootjdk
        uses: ./.github/actions/get-bootjdk
        with:
          platform: linux-x64

      - name: 'Install toolchain and dependencies'
        run: |
          echo "http://ports.ubuntu.com/ubuntu-ports/" | sudo tee -a /etc/apt/apt-mirrors.txt
          sudo dpkg --add-architecture armhf
          sudo apt-get update
          sudo apt-get install --only-upgrade apt
          sudo apt-get install libxrandr-dev:armhf libxtst-dev:armhf libasound2-dev:armhf ${{ inputs.apt-extra-packages }} autoconf python3 python-is-python3 unzip zip systemtap-sdt-dev libelf-dev:armhf libfontconfig1-dev:armhf libx11-dev:armhf libxext-dev:armhf libxrandr-dev:armhf libxrender-dev:armhf libxtst-dev:armhf libxt-dev:armhf

          echo "Downloading NDK"

          export NDK_VERSION=r27b

          wget -nc -nv -O android-ndk-$NDK_VERSION-linux-x86_64.zip "https://dl.google.com/android/repository/android-ndk-$NDK_VERSION-linux.zip"
          unzip -q android-ndk-$NDK_VERSION-linux-x86_64.zip
          export ANDROID_NDK_HOME=$PWD/android-ndk-$NDK_VERSION

          export BUILD_FREETYPE_VERSION="2.10.0"
          export TOOLCHAIN=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64

          cp devkit.info.arm ${TOOLCHAIN}

          export ANDROID_INCLUDE=$TOOLCHAIN/sysroot/usr

          export BUILD_FREETYPE_VERSION="2.10.0"

          wget https://downloads.sourceforge.net/project/freetype/freetype2/$BUILD_FREETYPE_VERSION/freetype-$BUILD_FREETYPE_VERSION.tar.gz
          tar xf freetype-$BUILD_FREETYPE_VERSION.tar.gz
          wget https://github.com/apple/cups/releases/download/v2.2.4/cups-2.2.4-source.tar.gz
          tar xf cups-2.2.4-source.tar.gz
          rm cups-2.2.4-source.tar.gz freetype-$BUILD_FREETYPE_VERSION.tar.gz

          cd freetype-$BUILD_FREETYPE_VERSION

          echo "Building Freetype"

          export PATH=$TOOLCHAIN/bin:$PATH
          ./configure \
            --host=$TARGET \
            --prefix=${PWD}/build_android-arm \
            --without-zlib \
            --with-png=no \
            --with-harfbuzz=no $EXTRA_ARGS \
            || error_code=$?

            if [[ "$error_code" -ne 0 ]]; then
              echo "\n\nCONFIGURE ERROR $error_code , config.log:"
              cat ${PWD}/builds/unix/config.log
              exit $error_code
            fi

            CFLAGS=-fno-rtti CXXFLAGS=-fno-rtti make -j4
            make install

      - name: 'Configure'
        run: | 
          export BUILD_FREETYPE_VERSION="2.10.0"
          export NDK_VERSION=r27b
          export ANDROID_NDK_HOME=$PWD/android-ndk-$NDK_VERSION
          export TOOLCHAIN=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64
          export ANDROID_INCLUDE=$TOOLCHAIN/sysroot/usr/include 

          export API=21
          export TARGET=armv7a-linux-androideabi

          export CPPFLAGS="-I$ANDROID_INCLUDE -I$ANDROID_INCLUDE/$TARGET -I/usr/include"
          export CPPFLAGS=""
          export LDFLAGS="-L/usr/lib"
          # Underlying compiler called by the wrappers
          export thecc=$TOOLCHAIN/bin/${TARGET}${API}-clang

          export thecxx=$TOOLCHAIN/bin/${TARGET}${API}-clang++

          # Configure and build.
          export AR=$TOOLCHAIN/bin/llvm-ar
          export AS=$TOOLCHAIN/bin/llvm-as
          export CC=$PWD/android-wrapped-clang
          export CXX=$PWD/android-wrapped-clang++
          export LD=$TOOLCHAIN/bin/ld
          export OBJCOPY=$TOOLCHAIN/bin/llvm-objcopy
          export RANLIB=$TOOLCHAIN/bin/llvm-ranlib
          export STRIP=$TOOLCHAIN/bin/llvm-strip

          export CFLAGS+=" -DLE_STANDALONE"
          export CFLAGS+=" -O3 -D__thumb__"

          chmod +x android-wrapped-clang
          chmod +x android-wrapped-clang++
          ln -s -f /usr/include/X11 $ANDROID_INCLUDE/
          ln -s -f /usr/include/fontconfig $ANDROID_INCLUDE/

          export CFLAGS+=" -mllvm -polly -DANDROID -Wno-error=implicit-function-declaration -Wno-error=int-conversion"
          export LDFLAGS+=" -L$PWD/dummy_libs -Wl,--undefined-version"

          export FREETYPE_DIR=$PWD/freetype-$BUILD_FREETYPE_VERSION/build_android-$TARGET_SHORT
          export CUPS_DIR=cups-2.2.4

          # Create dummy libraries so we won't have to remove them in OpenJDK makefiles
          mkdir -p dummy_libs
          ar cru dummy_libs/libpthread.a
          ar cru dummy_libs/librt.a
          ar cru dummy_libs/libthread_db.a

          # fix building libjawt
          ln -s -f $CUPS_DIR/cups $ANDROID_INCLUDE/

          bash configure \
            --with-conf-name=$TARGET \
            --openjdk-target=$TARGET \
            --with-boot-jdk=${{ steps.bootjdk.outputs.path }} \
            --with-extra-cflags="$CFLAGS" \
            --with-extra-cxxflags="$CFLAGS" \
            --with-extra-ldflags="$LDFLAGS" \
            --with-zlib=system \
            --with-jmod-compress=zip-1 \
            --with-version-opt=${{ matrix.debug-level }} \
            --with-gtest=${{ steps.gtest.outputs.path }} \
            --enable-headless-only \
            --x-includes=$ANDROID_INCLUDE/X11 \
            --enable-option-checking=fatal \
            --with-jvm-variants=client \
            --with-jvm-features=-dtrace,-zero,-vm-structs,-epsilongc \
            --with-devkit=$TOOLCHAIN \
            --with-native-debug-symbols=external \
            --disable-precompiled-headers \
            --with-fontconfig-include=$ANDROID_INCLUDE \
            --x-includes=$ANDROID_INCLUDE/X11 \
            --x-libraries=/usr/lib \
            --with-cups-include=$CUPS_DIR \
            --with-toolchain-type=gcc \
            OBJCOPY=${OBJCOPY} \
            RANLIB=${RANLIB} \
            AR=${AR} \
            STRIP=${STRIP} \
            --with-cups-include=$CUPS_DIR \
            ${{ matrix.flags }} \
            ${{ inputs.extra-conf-options }} ${{ inputs.configure-arguments }} || ( \
              echo "Dumping config.log:" && \
              cat config.log && \
              exit 1)

      - name: 'Build'
        id: build
        uses: ./.github/actions/do-build
        env:
          STATIC_LIBS: ${{ matrix.debug-level == 'release' && 'static-libs-bundles' || '' }}
        with:
          make-target: '${{ inputs.make-target }} ${STATIC_LIBS} ${{ inputs.make-arguments }}'
          platform: armhf
          debug-suffix: '${{ matrix.suffix }}'

      - name: 'Upload bundles'
        uses: ./.github/actions/upload-bundles
        with:
          platform: armhf
          debug-suffix: '${{ matrix.suffix }}'
